import { Press_Start_2P, Fira_Code } from "next/font/google";
import "./globals.css";
import MenuNavBar from "./components/MenuNavBar";

const pressStart2P = Press_Start_2P({
  weight: "400",
  variable: "--font-press-start-2p",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pressStart2P.variable} ${firaCode.variable}`}>
        <MenuNavBar />
        {children}
      </body>
    </html>
  );
}
